const actionTypes = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  REFRESH_TOKEN: "REFRESH_TOKEN",

  UPDATE_PROFILE: "UPDATE_PROFILE",
  ADD_FAVORITE: "ADD_FAVORITE",
  REMOVE_FAVORITE: "REMOVE_FAVORITE",
  ADD_MATCH_REQUEST_COUNT: "ADD_MATCH_REQUEST_COUNT",
  REMOVE_MATCH_REQUEST_COUNT: "REMOVE_MATCH_REQUEST_COUNT",
  ADD_MATCH_REQUEST_PENDING_COUNT: "ADD_MATCH_REQUEST_PENDING_COUNT",
  REMOVE_MATCH_REQUEST_PENDING_COUNT: "REMOVE_MATCH_REQUEST_PENDING_COUNT",
  ADD_COMMUNITY_COUNT: "ADD_COMMUNITY_COUNT",
  REMOVE_COMMUNITY_COUNT: "REMOVE_COMMUNITY_COUNT",

  UPDATE_NOTIFICATIONS: "UPDATE_NOTIFICATIONS",
  ADD_UNREAD_NOTIFICATIONS_COUNT: "ADD_UNREAD_NOTIFICATIONS_COUNT",
  REMOVE_UNREAD_NOTIFICATIONS_COUNT: "REMOVE_UNREAD_NOTIFICATIONS_COUNT",

  UPDATE_PERMISSION_NOTIFICATION: "UPDATE_PERMISSION_NOTIFICATION",

  UPDATE_LIST_ROOMS: "UPDATE_LIST_ROOMS",
  REMOVE_UNREAD_LISTROOMS_COUNT: "REMOVE_UNREAD_LISTROOMS_COUNT",
  ADD_UNREAD_LISTROOMS_COUNT: "ADD_UNREAD_LISTROOMS_COUNT",
};

export default actionTypes;
